# Generated by Django 4.0.5 on 2022-07-12 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clsUser',
            fields=[
                ('pk_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vhr_user_name', models.CharField(blank=True, max_length=30)),
                ('vhr_actual_name', models.CharField(blank=True, max_length=30)),
                ('vhr_password', models.CharField(blank=True, max_length=8)),
                ('int_if_admin', models.IntegerField()),
                ('dat_created_datetime', models.DateTimeField()),
                ('int_last_action', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clsEventDetails',
            fields=[
                ('pk_event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dat_event_start_date_time', models.DateTimeField()),
                ('dat_event_end_date_time', models.DateTimeField()),
                ('vhr_event_name', models.CharField(blank=True, max_length=30)),
                ('vhr_event_venue', models.CharField(blank=True, max_length=30)),
                ('vhr_event_description', models.TextField(blank=True, max_length=100)),
                ('vhr_event_image_upload', models.ImageField(upload_to='')),
                ('dat_created_datetime', models.DateTimeField()),
                ('int_last_action', models.IntegerField()),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.clsuser')),
            ],
        ),
    ]
