# Generated by Django 4.0.6 on 2022-07-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_rename_vhr_actual_name_clsuser_vhr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clseventdetails',
            name='vhr_event_description',
            field=models.TextField(),
        ),
    ]
